### ISSUE TITLE
OpenCV Installation - ModuleNotFoundError

### ISSUE THREAD

**Issue by kaytsui** [icr-ctl/scrubcam#1]
The following error occurs when installing opencv through the setup command `python setup.py develop`:

`ModuleNotFoundError: No module named 'skbuild'`

The [documentation](https://pypi.org/project/opencv-python/ ) says to upgrade pip with `pip install --upgrade pip` and to have version >= 19.3. However, my pip version was 21.1.3. 

Manually installing opencv using `pip install opencv-python` worked and did not result in the ModuleNotFoundError.

**Comment by iamgarcia** [comment]
Because OpenCV is part of the required dependencies in setup.py, `python setup.py develop` is no longer required to install OpenCV. The command to install the required dependencies, including OpenCV, is to run `python setup.py install`. Also, the newest version of OpenCV is unstable. The setup.py file will be updated so that it will install the last known stable OpenCV version instead of the most recent version.

**Comment by iamgarcia** [comment]
Correction: `python setup.py develop` and `python setup.py install` are deprecated commands. For users not using a Pi and installing ScrubCam, use `pip install .`. Otherwise, users using a Pi should use `pip install .[pi]`.
